### ISSUE TITLE
I'm getting NumberFormatException if I specify any integer parameters, such as "rows" or "retries"

### ISSUE THREAD

**Issue by uyilmaz** [sematext/solr-reindexer#2]
I'm getting NumberFormatException if I specify any integer parameters, such as "rows" or "retries". I think issue is due to the following line, parameter name is parsed instead of the parameter value:

https://github.com/sematext/solr-reindexer/blob/fefafaca2a14707c0de4648b9c9614747d8605ed/src/main/java/org/sematext/solr/reindexer/Runner.java#L113

**Comment by radu-gheorghe** [comment]
Thanks for reporting! It should be fixed in 1.2, which I'll release in a second.
